name: First Workflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print Greeting
        run: | 
            echo "Hellow World"
            echo "How ya doin?"
      - name: Pring goodbye
        run: echo "Done - bye!"
